# Generated by Django 3.0.3 on 2021-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=555)),
                ('country', models.CharField(max_length=555)),
                ('main', models.CharField(max_length=555)),
                ('wind', models.CharField(max_length=555)),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dt', models.CharField(max_length=50)),
            ],
        ),
    ]
